<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
        <ul class="app-menu">
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.index'))?'active':'' }}" href="{{ route('forex.index') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Forex Dashboard</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.index_liquidity'))?'active':'' }}" href="{{ route('forex.index_liquidity') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Index Liquidity </span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.currency_pair'))?'active':'' }}" href="{{ route('forex.currency_pair') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Currency Pairs Liquidity</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.index_frame'))?'active':'' }}" href="{{ route('forex.index_frame') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Index Frames</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.trading_live'))?'active':'' }}" href="{{ route('forex.trading_live') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Trading Live</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.US_Stocks'))?'active':'' }}" href="{{ route('forex.US_Stocks') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">US Stocks</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.market'))?'active':'' }}" href="{{ route('forex.market') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Market Indexes</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.Commodities'))?'active':'' }}" href="{{ route('forex.Commodities') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Commodities</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.Crypto'))?'active':'' }}" href="{{ route('forex.Crypto') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Crypto</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.commodities_dashboard'))?'active':'' }}" href="{{ route('forex.commodities_dashboard') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Commodities Dashboard</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.stocks_dashboard'))?'active':'' }}" href="{{ route('forex.stocks_dashboard') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label"> Stocks_Dashboard</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.crypto_dashboard'))?'active':'' }}" href="{{ route('forex.crypto_dashboard') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label"> crypto_Dashboard</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.USStocks_dashboard'))?'active':'' }}" href="{{ route('forex.USStocks_dashboard') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label"> USStocks_Dashboard</span></a></li>
            <li style="margin-top:5px"><a class="app-menu__item {{ url()->current()==url(route('forex.daily_market'))?'active':'' }}" href="{{ route('forex.daily_market') }}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Daily Market</span></a></li>
        </ul>
    </aside>
